[package]
name = "membrane_gif"
version = "0.1.1"
edition = "2021"
rust-version = "1.88"
publish = false

[lib]
name = "membrane_gif"
crate-type = ["cdylib", "rlib"]

[dependencies]
gif = "0.14.2"
rustler = "0.34.0"
yuv = { version = "0.8.17", features = ["big_endian"] }

[dev-dependencies]
rstest = { version = "0.27.0", default-features = false }
